[build]
  publish = "."
  
[dev]
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "openai",
    "pdf-parse",
    "mammoth",
    "pptx2json",
    "officeparser",
    "xlsx",
    "tesseract.js",
    "langchain"
  ]
  included_files = [
    "netlify/functions/*",
    "node_modules/pdf-parse/**/*"
  ]

[functions."ask"]
  timeout = 26
