[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai", "pdf-parse"]
  included_files = [
    "netlify/functions/*",
    "node_modules/pdf-parse/**/*"
  ]

[functions."ask"]
  timeout = 26
