[build]
  publish = "."

[dev]
  publish = "."

[functions."*"]
included_files = ["netlify/functions/*", "node_modules/pdf-parse/**/*"]
external_node_modules = [
  "openai", 
  "pdf-parse", 
  "mammoth", 
  "pptx2json", 
  "officeparser", 
  "xlsx", 
  "tesseract.js", 
  "tesseract.js/dist/worker.min.js", 
  "langchain"
]
node_bundler = "esbuild"

[functions."ask"]
  timeout = 26

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
