[build]
  publish = "."

[dev]
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "openai",
    "pdf-parse"
  ]
  included_files = [
    "netlify/functions/*",
    "node_modules/pdf-parse/**/*"
  ]

[functions."ask"]
  timeout = 26

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
